//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personas", Namespace="http://tempuri.org/")]
    public partial class Personas : object
    {
        
        private int idField;
        
        private string CuilField;
        
        private string ApellidoYNombreField;
        
        private System.DateTime FechaNacimientoField;
        
        private int idZonaField;
        
        private string ZonaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cuil
        {
            get
            {
                return this.CuilField;
            }
            set
            {
                this.CuilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApellidoYNombre
        {
            get
            {
                return this.ApellidoYNombreField;
            }
            set
            {
                this.ApellidoYNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int idZona
        {
            get
            {
                return this.idZonaField;
            }
            set
            {
                this.idZonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Zona
        {
            get
            {
                return this.ZonaField;
            }
            set
            {
                this.ZonaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zonas", Namespace="http://tempuri.org/")]
    public partial class Zonas : object
    {
        
        private int idzonaField;
        
        private string zonaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idzona
        {
            get
            {
                return this.idzonaField;
            }
            set
            {
                this.idzonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string zona
        {
            get
            {
                return this.zonaField;
            }
            set
            {
                this.zonaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PracticaWS.PracticaWSSoap")]
    public interface PracticaWSSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ApellidoYNombre del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPersonas", ReplyAction="*")]
        PracticaWS.ObtenerPersonasResponse ObtenerPersonas(PracticaWS.ObtenerPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<PracticaWS.ObtenerPersonasResponse> ObtenerPersonasAsync(PracticaWS.ObtenerPersonasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerZonasResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerZonas", ReplyAction="*")]
        PracticaWS.ObtenerZonasResponse ObtenerZonas(PracticaWS.ObtenerZonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerZonas", ReplyAction="*")]
        System.Threading.Tasks.Task<PracticaWS.ObtenerZonasResponse> ObtenerZonasAsync(PracticaWS.ObtenerZonasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nueva del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarPersonas", ReplyAction="*")]
        PracticaWS.RegistrarPersonasResponse RegistrarPersonas(PracticaWS.RegistrarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<PracticaWS.RegistrarPersonasResponse> RegistrarPersonasAsync(PracticaWS.RegistrarPersonasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento modifica del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPersonas", ReplyAction="*")]
        PracticaWS.ModificarPersonasResponse ModificarPersonas(PracticaWS.ModificarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<PracticaWS.ModificarPersonasResponse> ModificarPersonasAsync(PracticaWS.ModificarPersonasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento elimina del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersonas", ReplyAction="*")]
        PracticaWS.EliminarPersonasResponse EliminarPersonas(PracticaWS.EliminarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<PracticaWS.EliminarPersonasResponse> EliminarPersonasAsync(PracticaWS.EliminarPersonasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nueva del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarZonas", ReplyAction="*")]
        PracticaWS.RegistrarZonasResponse RegistrarZonas(PracticaWS.RegistrarZonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarZonas", ReplyAction="*")]
        System.Threading.Tasks.Task<PracticaWS.RegistrarZonasResponse> RegistrarZonasAsync(PracticaWS.RegistrarZonasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento modifica del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarZonas", ReplyAction="*")]
        PracticaWS.ModificarZonasResponse ModificarZonas(PracticaWS.ModificarZonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarZonas", ReplyAction="*")]
        System.Threading.Tasks.Task<PracticaWS.ModificarZonasResponse> ModificarZonasAsync(PracticaWS.ModificarZonasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento elimina del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarZonas", ReplyAction="*")]
        PracticaWS.EliminarZonasResponse EliminarZonas(PracticaWS.EliminarZonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarZonas", ReplyAction="*")]
        System.Threading.Tasks.Task<PracticaWS.EliminarZonasResponse> EliminarZonasAsync(PracticaWS.EliminarZonasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPersonasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPersonas", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.ObtenerPersonasRequestBody Body;
        
        public ObtenerPersonasRequest()
        {
        }
        
        public ObtenerPersonasRequest(PracticaWS.ObtenerPersonasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPersonasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApellidoYNombre;
        
        public ObtenerPersonasRequestBody()
        {
        }
        
        public ObtenerPersonasRequestBody(string ApellidoYNombre)
        {
            this.ApellidoYNombre = ApellidoYNombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPersonasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPersonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.ObtenerPersonasResponseBody Body;
        
        public ObtenerPersonasResponse()
        {
        }
        
        public ObtenerPersonasResponse(PracticaWS.ObtenerPersonasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPersonasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Personas[] ObtenerPersonasResult;
        
        public ObtenerPersonasResponseBody()
        {
        }
        
        public ObtenerPersonasResponseBody(PracticaWS.Personas[] ObtenerPersonasResult)
        {
            this.ObtenerPersonasResult = ObtenerPersonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerZonasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerZonas", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.ObtenerZonasRequestBody Body;
        
        public ObtenerZonasRequest()
        {
        }
        
        public ObtenerZonasRequest(PracticaWS.ObtenerZonasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerZonasRequestBody
    {
        
        public ObtenerZonasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerZonasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerZonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.ObtenerZonasResponseBody Body;
        
        public ObtenerZonasResponse()
        {
        }
        
        public ObtenerZonasResponse(PracticaWS.ObtenerZonasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerZonasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Zonas[] ObtenerZonasResult;
        
        public ObtenerZonasResponseBody()
        {
        }
        
        public ObtenerZonasResponseBody(PracticaWS.Zonas[] ObtenerZonasResult)
        {
            this.ObtenerZonasResult = ObtenerZonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarPersonasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarPersonas", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.RegistrarPersonasRequestBody Body;
        
        public RegistrarPersonasRequest()
        {
        }
        
        public RegistrarPersonasRequest(PracticaWS.RegistrarPersonasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarPersonasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Personas nueva;
        
        public RegistrarPersonasRequestBody()
        {
        }
        
        public RegistrarPersonasRequestBody(PracticaWS.Personas nueva)
        {
            this.nueva = nueva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarPersonasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarPersonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.RegistrarPersonasResponseBody Body;
        
        public RegistrarPersonasResponse()
        {
        }
        
        public RegistrarPersonasResponse(PracticaWS.RegistrarPersonasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarPersonasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Personas RegistrarPersonasResult;
        
        public RegistrarPersonasResponseBody()
        {
        }
        
        public RegistrarPersonasResponseBody(PracticaWS.Personas RegistrarPersonasResult)
        {
            this.RegistrarPersonasResult = RegistrarPersonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarPersonasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarPersonas", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.ModificarPersonasRequestBody Body;
        
        public ModificarPersonasRequest()
        {
        }
        
        public ModificarPersonasRequest(PracticaWS.ModificarPersonasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarPersonasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Personas modifica;
        
        public ModificarPersonasRequestBody()
        {
        }
        
        public ModificarPersonasRequestBody(PracticaWS.Personas modifica)
        {
            this.modifica = modifica;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarPersonasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarPersonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.ModificarPersonasResponseBody Body;
        
        public ModificarPersonasResponse()
        {
        }
        
        public ModificarPersonasResponse(PracticaWS.ModificarPersonasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarPersonasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Personas ModificarPersonasResult;
        
        public ModificarPersonasResponseBody()
        {
        }
        
        public ModificarPersonasResponseBody(PracticaWS.Personas ModificarPersonasResult)
        {
            this.ModificarPersonasResult = ModificarPersonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPersonasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPersonas", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.EliminarPersonasRequestBody Body;
        
        public EliminarPersonasRequest()
        {
        }
        
        public EliminarPersonasRequest(PracticaWS.EliminarPersonasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarPersonasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Personas elimina;
        
        public EliminarPersonasRequestBody()
        {
        }
        
        public EliminarPersonasRequestBody(PracticaWS.Personas elimina)
        {
            this.elimina = elimina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPersonasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPersonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.EliminarPersonasResponseBody Body;
        
        public EliminarPersonasResponse()
        {
        }
        
        public EliminarPersonasResponse(PracticaWS.EliminarPersonasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarPersonasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Personas EliminarPersonasResult;
        
        public EliminarPersonasResponseBody()
        {
        }
        
        public EliminarPersonasResponseBody(PracticaWS.Personas EliminarPersonasResult)
        {
            this.EliminarPersonasResult = EliminarPersonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarZonasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarZonas", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.RegistrarZonasRequestBody Body;
        
        public RegistrarZonasRequest()
        {
        }
        
        public RegistrarZonasRequest(PracticaWS.RegistrarZonasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarZonasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Zonas nueva;
        
        public RegistrarZonasRequestBody()
        {
        }
        
        public RegistrarZonasRequestBody(PracticaWS.Zonas nueva)
        {
            this.nueva = nueva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarZonasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarZonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.RegistrarZonasResponseBody Body;
        
        public RegistrarZonasResponse()
        {
        }
        
        public RegistrarZonasResponse(PracticaWS.RegistrarZonasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarZonasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Zonas RegistrarZonasResult;
        
        public RegistrarZonasResponseBody()
        {
        }
        
        public RegistrarZonasResponseBody(PracticaWS.Zonas RegistrarZonasResult)
        {
            this.RegistrarZonasResult = RegistrarZonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarZonasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarZonas", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.ModificarZonasRequestBody Body;
        
        public ModificarZonasRequest()
        {
        }
        
        public ModificarZonasRequest(PracticaWS.ModificarZonasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarZonasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Zonas modifica;
        
        public ModificarZonasRequestBody()
        {
        }
        
        public ModificarZonasRequestBody(PracticaWS.Zonas modifica)
        {
            this.modifica = modifica;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarZonasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarZonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.ModificarZonasResponseBody Body;
        
        public ModificarZonasResponse()
        {
        }
        
        public ModificarZonasResponse(PracticaWS.ModificarZonasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarZonasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Zonas ModificarZonasResult;
        
        public ModificarZonasResponseBody()
        {
        }
        
        public ModificarZonasResponseBody(PracticaWS.Zonas ModificarZonasResult)
        {
            this.ModificarZonasResult = ModificarZonasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarZonasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarZonas", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.EliminarZonasRequestBody Body;
        
        public EliminarZonasRequest()
        {
        }
        
        public EliminarZonasRequest(PracticaWS.EliminarZonasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarZonasRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Zonas elimina;
        
        public EliminarZonasRequestBody()
        {
        }
        
        public EliminarZonasRequestBody(PracticaWS.Zonas elimina)
        {
            this.elimina = elimina;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarZonasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarZonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PracticaWS.EliminarZonasResponseBody Body;
        
        public EliminarZonasResponse()
        {
        }
        
        public EliminarZonasResponse(PracticaWS.EliminarZonasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarZonasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PracticaWS.Zonas EliminarZonasResult;
        
        public EliminarZonasResponseBody()
        {
        }
        
        public EliminarZonasResponseBody(PracticaWS.Zonas EliminarZonasResult)
        {
            this.EliminarZonasResult = EliminarZonasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface PracticaWSSoapChannel : PracticaWS.PracticaWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PracticaWSSoapClient : System.ServiceModel.ClientBase<PracticaWS.PracticaWSSoap>, PracticaWS.PracticaWSSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PracticaWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PracticaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), PracticaWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PracticaWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PracticaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PracticaWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PracticaWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PracticaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PracticaWS.ObtenerPersonasResponse PracticaWS.PracticaWSSoap.ObtenerPersonas(PracticaWS.ObtenerPersonasRequest request)
        {
            return base.Channel.ObtenerPersonas(request);
        }
        
        public PracticaWS.Personas[] ObtenerPersonas(string ApellidoYNombre)
        {
            PracticaWS.ObtenerPersonasRequest inValue = new PracticaWS.ObtenerPersonasRequest();
            inValue.Body = new PracticaWS.ObtenerPersonasRequestBody();
            inValue.Body.ApellidoYNombre = ApellidoYNombre;
            PracticaWS.ObtenerPersonasResponse retVal = ((PracticaWS.PracticaWSSoap)(this)).ObtenerPersonas(inValue);
            return retVal.Body.ObtenerPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PracticaWS.ObtenerPersonasResponse> PracticaWS.PracticaWSSoap.ObtenerPersonasAsync(PracticaWS.ObtenerPersonasRequest request)
        {
            return base.Channel.ObtenerPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PracticaWS.ObtenerPersonasResponse> ObtenerPersonasAsync(string ApellidoYNombre)
        {
            PracticaWS.ObtenerPersonasRequest inValue = new PracticaWS.ObtenerPersonasRequest();
            inValue.Body = new PracticaWS.ObtenerPersonasRequestBody();
            inValue.Body.ApellidoYNombre = ApellidoYNombre;
            return ((PracticaWS.PracticaWSSoap)(this)).ObtenerPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PracticaWS.ObtenerZonasResponse PracticaWS.PracticaWSSoap.ObtenerZonas(PracticaWS.ObtenerZonasRequest request)
        {
            return base.Channel.ObtenerZonas(request);
        }
        
        public PracticaWS.Zonas[] ObtenerZonas()
        {
            PracticaWS.ObtenerZonasRequest inValue = new PracticaWS.ObtenerZonasRequest();
            inValue.Body = new PracticaWS.ObtenerZonasRequestBody();
            PracticaWS.ObtenerZonasResponse retVal = ((PracticaWS.PracticaWSSoap)(this)).ObtenerZonas(inValue);
            return retVal.Body.ObtenerZonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PracticaWS.ObtenerZonasResponse> PracticaWS.PracticaWSSoap.ObtenerZonasAsync(PracticaWS.ObtenerZonasRequest request)
        {
            return base.Channel.ObtenerZonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PracticaWS.ObtenerZonasResponse> ObtenerZonasAsync()
        {
            PracticaWS.ObtenerZonasRequest inValue = new PracticaWS.ObtenerZonasRequest();
            inValue.Body = new PracticaWS.ObtenerZonasRequestBody();
            return ((PracticaWS.PracticaWSSoap)(this)).ObtenerZonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PracticaWS.RegistrarPersonasResponse PracticaWS.PracticaWSSoap.RegistrarPersonas(PracticaWS.RegistrarPersonasRequest request)
        {
            return base.Channel.RegistrarPersonas(request);
        }
        
        public PracticaWS.Personas RegistrarPersonas(PracticaWS.Personas nueva)
        {
            PracticaWS.RegistrarPersonasRequest inValue = new PracticaWS.RegistrarPersonasRequest();
            inValue.Body = new PracticaWS.RegistrarPersonasRequestBody();
            inValue.Body.nueva = nueva;
            PracticaWS.RegistrarPersonasResponse retVal = ((PracticaWS.PracticaWSSoap)(this)).RegistrarPersonas(inValue);
            return retVal.Body.RegistrarPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PracticaWS.RegistrarPersonasResponse> PracticaWS.PracticaWSSoap.RegistrarPersonasAsync(PracticaWS.RegistrarPersonasRequest request)
        {
            return base.Channel.RegistrarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PracticaWS.RegistrarPersonasResponse> RegistrarPersonasAsync(PracticaWS.Personas nueva)
        {
            PracticaWS.RegistrarPersonasRequest inValue = new PracticaWS.RegistrarPersonasRequest();
            inValue.Body = new PracticaWS.RegistrarPersonasRequestBody();
            inValue.Body.nueva = nueva;
            return ((PracticaWS.PracticaWSSoap)(this)).RegistrarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PracticaWS.ModificarPersonasResponse PracticaWS.PracticaWSSoap.ModificarPersonas(PracticaWS.ModificarPersonasRequest request)
        {
            return base.Channel.ModificarPersonas(request);
        }
        
        public PracticaWS.Personas ModificarPersonas(PracticaWS.Personas modifica)
        {
            PracticaWS.ModificarPersonasRequest inValue = new PracticaWS.ModificarPersonasRequest();
            inValue.Body = new PracticaWS.ModificarPersonasRequestBody();
            inValue.Body.modifica = modifica;
            PracticaWS.ModificarPersonasResponse retVal = ((PracticaWS.PracticaWSSoap)(this)).ModificarPersonas(inValue);
            return retVal.Body.ModificarPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PracticaWS.ModificarPersonasResponse> PracticaWS.PracticaWSSoap.ModificarPersonasAsync(PracticaWS.ModificarPersonasRequest request)
        {
            return base.Channel.ModificarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PracticaWS.ModificarPersonasResponse> ModificarPersonasAsync(PracticaWS.Personas modifica)
        {
            PracticaWS.ModificarPersonasRequest inValue = new PracticaWS.ModificarPersonasRequest();
            inValue.Body = new PracticaWS.ModificarPersonasRequestBody();
            inValue.Body.modifica = modifica;
            return ((PracticaWS.PracticaWSSoap)(this)).ModificarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PracticaWS.EliminarPersonasResponse PracticaWS.PracticaWSSoap.EliminarPersonas(PracticaWS.EliminarPersonasRequest request)
        {
            return base.Channel.EliminarPersonas(request);
        }
        
        public PracticaWS.Personas EliminarPersonas(PracticaWS.Personas elimina)
        {
            PracticaWS.EliminarPersonasRequest inValue = new PracticaWS.EliminarPersonasRequest();
            inValue.Body = new PracticaWS.EliminarPersonasRequestBody();
            inValue.Body.elimina = elimina;
            PracticaWS.EliminarPersonasResponse retVal = ((PracticaWS.PracticaWSSoap)(this)).EliminarPersonas(inValue);
            return retVal.Body.EliminarPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PracticaWS.EliminarPersonasResponse> PracticaWS.PracticaWSSoap.EliminarPersonasAsync(PracticaWS.EliminarPersonasRequest request)
        {
            return base.Channel.EliminarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PracticaWS.EliminarPersonasResponse> EliminarPersonasAsync(PracticaWS.Personas elimina)
        {
            PracticaWS.EliminarPersonasRequest inValue = new PracticaWS.EliminarPersonasRequest();
            inValue.Body = new PracticaWS.EliminarPersonasRequestBody();
            inValue.Body.elimina = elimina;
            return ((PracticaWS.PracticaWSSoap)(this)).EliminarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PracticaWS.RegistrarZonasResponse PracticaWS.PracticaWSSoap.RegistrarZonas(PracticaWS.RegistrarZonasRequest request)
        {
            return base.Channel.RegistrarZonas(request);
        }
        
        public PracticaWS.Zonas RegistrarZonas(PracticaWS.Zonas nueva)
        {
            PracticaWS.RegistrarZonasRequest inValue = new PracticaWS.RegistrarZonasRequest();
            inValue.Body = new PracticaWS.RegistrarZonasRequestBody();
            inValue.Body.nueva = nueva;
            PracticaWS.RegistrarZonasResponse retVal = ((PracticaWS.PracticaWSSoap)(this)).RegistrarZonas(inValue);
            return retVal.Body.RegistrarZonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PracticaWS.RegistrarZonasResponse> PracticaWS.PracticaWSSoap.RegistrarZonasAsync(PracticaWS.RegistrarZonasRequest request)
        {
            return base.Channel.RegistrarZonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PracticaWS.RegistrarZonasResponse> RegistrarZonasAsync(PracticaWS.Zonas nueva)
        {
            PracticaWS.RegistrarZonasRequest inValue = new PracticaWS.RegistrarZonasRequest();
            inValue.Body = new PracticaWS.RegistrarZonasRequestBody();
            inValue.Body.nueva = nueva;
            return ((PracticaWS.PracticaWSSoap)(this)).RegistrarZonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PracticaWS.ModificarZonasResponse PracticaWS.PracticaWSSoap.ModificarZonas(PracticaWS.ModificarZonasRequest request)
        {
            return base.Channel.ModificarZonas(request);
        }
        
        public PracticaWS.Zonas ModificarZonas(PracticaWS.Zonas modifica)
        {
            PracticaWS.ModificarZonasRequest inValue = new PracticaWS.ModificarZonasRequest();
            inValue.Body = new PracticaWS.ModificarZonasRequestBody();
            inValue.Body.modifica = modifica;
            PracticaWS.ModificarZonasResponse retVal = ((PracticaWS.PracticaWSSoap)(this)).ModificarZonas(inValue);
            return retVal.Body.ModificarZonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PracticaWS.ModificarZonasResponse> PracticaWS.PracticaWSSoap.ModificarZonasAsync(PracticaWS.ModificarZonasRequest request)
        {
            return base.Channel.ModificarZonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PracticaWS.ModificarZonasResponse> ModificarZonasAsync(PracticaWS.Zonas modifica)
        {
            PracticaWS.ModificarZonasRequest inValue = new PracticaWS.ModificarZonasRequest();
            inValue.Body = new PracticaWS.ModificarZonasRequestBody();
            inValue.Body.modifica = modifica;
            return ((PracticaWS.PracticaWSSoap)(this)).ModificarZonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PracticaWS.EliminarZonasResponse PracticaWS.PracticaWSSoap.EliminarZonas(PracticaWS.EliminarZonasRequest request)
        {
            return base.Channel.EliminarZonas(request);
        }
        
        public PracticaWS.Zonas EliminarZonas(PracticaWS.Zonas elimina)
        {
            PracticaWS.EliminarZonasRequest inValue = new PracticaWS.EliminarZonasRequest();
            inValue.Body = new PracticaWS.EliminarZonasRequestBody();
            inValue.Body.elimina = elimina;
            PracticaWS.EliminarZonasResponse retVal = ((PracticaWS.PracticaWSSoap)(this)).EliminarZonas(inValue);
            return retVal.Body.EliminarZonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PracticaWS.EliminarZonasResponse> PracticaWS.PracticaWSSoap.EliminarZonasAsync(PracticaWS.EliminarZonasRequest request)
        {
            return base.Channel.EliminarZonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PracticaWS.EliminarZonasResponse> EliminarZonasAsync(PracticaWS.Zonas elimina)
        {
            PracticaWS.EliminarZonasRequest inValue = new PracticaWS.EliminarZonasRequest();
            inValue.Body = new PracticaWS.EliminarZonasRequestBody();
            inValue.Body.elimina = elimina;
            return ((PracticaWS.PracticaWSSoap)(this)).EliminarZonasAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PracticaWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PracticaWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PracticaWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63923/PracticaWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PracticaWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63923/PracticaWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PracticaWSSoap,
            
            PracticaWSSoap12,
        }
    }
}
